#!/usr/bin/env bash
# This script useses trap to trap signal

function sigterm_handler()
{
	echo "I am invincible!!!"
}

trap 'sigterm_handler' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
