#!/usr/bin/env bash
# This script display "Best School" followed by hi at 9th loop

count=1
while [ $count -le 10 ]; do
	if [ $count -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi

	((count++))
done
