#!/usr/bin/env bash
# This scripts checks if file exist and prints info about the file

if [ -e "school" ]; then

	if [ -f "school" ]; then
		echo "school file exists"

		if [ -s "school" ]; then
			echo "school file is not empty"
		else
			echo "school file is empty"
		fi
		echo "school is a regular file"

	elif [ -d "school" ]; then
		echo "school file exists"
		echo "school file is not empty"
	fi
else
	echo "school file does not exist"
fi
