#!/usr/bin/env bash
# This script changes your localhost

cp /etc/hosts /etc/hosts.backup
cp /etc/hosts ~/hosts.lp
sed -i "s/127.0.0.1/127.0.0.2/" ~/hosts.lp
sed -i "2i8.8.8.8 facebook.com" ~/hosts.lp
cp -f ~/hosts.lp /etc/hosts
