#!/usr/bin/env bash
# this script run nginx as ngunx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default

chmod 644 /etc/nginx/nginx.conf

pkill apache2

sudo -u nginx service nginx start
